
-- CRIANDO A PROCEDURE
CREATE PROCEDURE [dbo].[BuscaPorEntidades2] @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
	SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO
	FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
	SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO
	FROM [TABELA DE VENDEDORES]
END
GO


EXEC BuscaPorEntidades2 'clientes'

-- ALTERANDO A PROCEDURE.
ALTER PROCEDURE [dbo].[BuscaPorEntidades2] @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
	SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR
	FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
	SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS DESCRITOR
	FROM [TABELA DE VENDEDORES]
END
GO