/*Crie uma variável chamada NUMNOTAS e atribua a ela o número de notas fiscais do dia 01/01/2017. Mostre na saída do script o valor da variável.*/

-- DECLARANDO VARIÁVEL NUMNOTAS
DECLARE @NUMNOTAS INT

-- VARIÁVEL @NUMNOTAS VAI RECEBER A CONTAGEM DO NÚMERO DE NOTAS ONDE A DATA É '2017-01-01'.
SELECT 
@NUMNOTAS=COUNT(NUMERO)
FROM [NOTAS FISCAIS]
WHERE [DATA] = '20170101'

-- MOSTRA O RESULTADO DA VARIÁVEL '@NUMNOTAS'
PRINT @NUMNOTAS