-- CRIAR PROCEDURE COM TRATAMENTO TRY-CATCH
CREATE PROCEDURE TrataErroZeroTry2 @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@MENSAGEM VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
		SUM(A.QUANTIDADE * A.[PREÇO]) / @DENOMINADOR AS COMISSAO
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO
		WHERE B.CPF = @CPF AND YEAR(B.[DATA]) = @ANO
	END TRY
	BEGIN CATCH
		-- OBSERVE QUE LÁ NA CREATE PROCEDURE A VARIÁVEL ESTÁ COM VARCHAR DE (MAX) PARA NÃO LIMITAR A QUANTIDADE DE MENSAGEM QUE SERÁ INCLUSA NESTE BLOCO ABAIXO.
		SET @MENSAGEM = 'HOUVE UM ERRO NÚMERO: ' + CONVERT(VARCHAR(10), ERROR_NUMBER()) + ' - '
		SET @MENSAGEM = @MENSAGEM + ' MENSAGEM: ' + ERROR_MESSAGE() + ' - '
		SET @MENSAGEM = @MENSAGEM + ' GRAU DE SEVERIDADE DO ERRO: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - '
		SET @MENSAGEM = @MENSAGEM + ' ESTADO DO ERRO: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + ' NÚMERO DA LINHA: ' + CONVERT(VARCHAR(10), ERROR_LINE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + ' PROCEDURE: ' + ERROR_PROCEDURE() 
	END CATCH
END

DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @MENSAGEM VARCHAR(MAX)

SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MENSAGEM = ''
EXEC TrataErroZeroTry2 @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR, @MENSAGEM = @MENSAGEM OUTPUT

-- EXIBIDO EM MENSAGEM
IF @MENSAGEM <> ''
	PRINT @MENSAGEM	