-- SE 'TABELA_TESTE' NÃO FOR NULO EXECUTA O DROP TABLE(APAGA A TABELA).
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE

-- SE TABELA TESTE FOR NULO(NÃO EXISTIR) CREATE TABLE(CRIA TABELA_TESTE).
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10))
