-- ATRIBUINDO VALORES AS VARIÁVEIS
SET @MATRICULA = '00240'
SET @NOME = 'Cláudia Rodrigues'
SET @PERCENTUAL = 0.10
SET @DATA = '20120312'
SET @FERIAS = 1
SET @BAIRRO = 'Jardins'
-- INSERÇÃO DE VALORES COM VARIÁVEIS
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

-- CONSULTANDO DADOS PARA CONFIRMAR SE HOUVE A INCLUSÃO
SELECT 
   MATRICULA
 , NOME
 , [PERCENTUAL COMISSÃO]
 , [DATA ADMISSÃO]
 , [DE FERIAS]
 , BAIRRO
FROM [TABELA DE VENDEDORES]