-- CRIANDO TABELA TEMPORÁRIA
CREATE TABLE #TABELA01 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)

INSERT INTO #TABELA01 (ID, NOME) VALUES('1','JOÃO')

INSERT INTO #TABELA01 (ID, NOME) VALUES('2','PEDRO') 

SELECT * FROM #TABELA01