-- DECLARANDO VARIÁVEL LIMITE MÍNIMO E MÁXIMO
DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT

-- ATRIBUINDO VALORES PARA AMBOS
SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10

-- ENQUANTO 'LIMITE MÍNIMO' FOR MENOR QUE 'LÍMITE MÁXIMO' "IMPRIME" O NÚMERO E ADICIONA +1. SE LIMITE MINIMO FOR IGUAL A 6, PARA EXECUÇÃO DO LOOP
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO += 1
	IF @LIMITE_MINIMO = 6
		BREAK
END