/*Crie um script que, baseado em uma data, conte o número de notas fiscais. Se houver mais de 70 notas, exiba a mensagem "Muita nota". Se não, exiba a mensagem "Pouca nota". Exiba também o número de notas.*/

--DECLARANDO VARIÁVEIS NÚMERO DE NOTAS E DATA
DECLARE @DATA DATE
DECLARE @NUMNOTAS INT
--'@DATA' VAI RECEBER O VALOR DE DATA
SET @DATA = '20170105'

-- ATRIBUINDO A CONTAGEM DENTRO DA VARIÁVEL '@NUMNOTAS' E FAZENDO FILTRO POR DATA
SELECT 
   @NUMNOTAS = COUNT(NUMERO)
FROM [NOTAS FISCAIS]
WHERE DATA = @DATA

-- "IMPRIME" VALOR RECEBIDO DE NUMNOTAS
PRINT @NUMNOTAS

-- SE @NUMNOTAS FOR MAIOR QUE 70, "IMPRIME": 'MUITA NOTA'. SE NÃO "IMPRIME": 'POUCA NOTA'
IF @NUMNOTAS > 70
	PRINT 'MUITA NOTA'
ELSE 
	PRINT 'POUCA NOTA'